common:
  author: MIRACUM-Pipe
  center: MIRACUM-Pipe
  dirTmp: /tmp
  memory: 8g
  cpucores: 4
  files:
    # filenames of the input files as fastq.gz
    tumor_R1: tumor_R1.fastq.gz
    tumor_R2: tumor_R2.fastq.gz
    germline_R1: germline_R1.fastq.gz
    germline_R2: germline_R2.fastq.gz
    panel:
        # base filenames of the input files, e.g. sample_ID_DNA_S7_L00 for sample_ID_DNA_S7_L001_R1_001.fastq.gz, and provide the number of paired-end files, i.e. only give the number for one direction (R1 or R2)
        tumor: Sample_ID_DNA_S7_L00
        numberOfFiles: 4
  entity: Other
  RNA:
    # folder contatining RNA fastq files for RNA fusions
    folder: RNA
  protocol: wes
  # process and annotate germline file, allowed values: yes, no
  # set to no if the germline sample should be used only to identify somatic variants
  germline: yes
  # ucsc mysql server can also be hosted local e.g. using https://github.com/nr23730/ucsc-hg19-refgene
  ucscServer: genome-euro-mysql.soe.ucsc.edu
  # Mapping of CNV regions (chr, start, end) to genes; allowed values: online / offline
  cnvAnnotation: online

sex: 0

general:
  # minimum base quality to call a variant
  minBaseQual: 28
  # minimum population frequency from genomAD_genome; AF_popmax
  maf_cutoff: 0.001
  # minimum variant allele / tumor frequency to call a variant
  minVAF: 0.05
  minGermlineVAF: 0.25

wes:  
  mutect:
    #--base-quality-score-threshold 28; Base qualities below this threshold will be reduced to the minimum (6)  Default value: 18
    #--callable-depth 8; Minimum depth to be considered callable for Mutect stats.  Does not affect genotyping. Default value: 10
    callableDepth: 8
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-base-quality-score 28; Minimum base quality required to consider a base for calling  Default value: 10

    #--panel-of-normals; VCF file of sites observed in normal.  Default value: null
    panelOfNormals: somatic-b37_Mutect2-exome-panel.vcf
    #--germline-resource; Population vcf of germline sequencing containing allele fractions.  Default value: null
    germlineResource: somatic-b37_af-only-gnomad.raw.sites.vcf

  filterMutectCalls:
    #--contamination-estimate 0.5?; Estimate of contamination.  Default value: 0.0 (evtl. tumor purity)
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-allele-fraction 0.05; Minimum allele fraction required  Default value: 0.0 (VAF?)
    #--min-median-base-quality 28; Minimum median base quality of alt reads  Default value: 20

  ControlFREEC:
    # desired behavior in the ambiguous regions (poly-N or low mappability regions between two different copy number values)
    # 0: the "unknown" region is attached to the "known" region on the right
    # 1: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one
    # 2: make a separate fragment of this unknown region and then attaches it to the left or to the right region but the ploidy copy number has a priority
    # 3: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one but this known region should make at least half-size of the unknown region
    # 4: make a separate fragment of this unknown region and do not assign any copy number to this region at all
    breakPointType: 4
    # positive value of threshold for segmentation of normalized profiles
    breakPointThreshold: 1.2
    # set to 1 or 2 to correct the Read Count (RC) for GC-content bias and low mappability even when you have a control sample
    # 0: simply model "sample RC ~ Control RC"
    # 1: normalize the sample and the control RC using GC-content and then calculate the ratio "Sample RC/contol RC"
    # 2: model "sample RC ~ Control RC" bias, and then normalize for GC-content
    forceGCcontentNormalization: 1
    # intercept of polynomial
    # 1 - with GC-content,
    # 0 - with a control dataset
    intercept: 0
    # minimal number of consecutive windows to call a CNA
    # 3 for WES and 1 for WGS
    minCNAlength: 3
    # maxThreads: 12 -> cpucores
    # set TRUE for target resequencing data (e.g., exome-seq) to avoid false positive predictions due to non-uniform capture
    noisyData: TRUE
    # genome ploidy; In case of doubt, you can set different values and Control-FREEC will select the one that explains most observed CNAs
    ploidy: 2
    # set FALSE to avoid printing "-1" to the _ratio.txt files. Useful for exome-seq or targeted sequencing data
    printNA: FALSE
    # threshold on the minimal number of reads per window in the control sample
    # Useful for exome-seq or targeted sequencing data
    # recommended value >=50 for for exome data
    readCountThreshold: 50
    # step (used only when "window" is specified); do not use for exome sequencing (instead set "window=0")
    step: 0
    # explicit window size (higher priority than coefficientOfVariation);
    # for whole genome sequencing: "window=50000"
    # for whole exome sequencing: "window=0"
    window: 0
    # Use a mappability profile to correct read counts (in this case a mappability file must be provided with "gemMappabilityFile" )
    uniqueMatch: TRUE
    # set TRUE to correct for contamination by normal cells.
    # If "contamination" is not provided, it will automatically evaluate the level of contamination
    contaminationAdjustment: TRUE

## Panel Parameters
panel:
  mutect:
    #--base-quality-score-threshold 28; Base qualities below this threshold will be reduced to the minimum (6)  Default value: 18
    #--callable-depth 8; Minimum depth to be considered callable for Mutect stats.  Does not affect genotyping. Default value: 10
    callableDepth: 50
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-base-quality-score 28; Minimum base quality required to consider a base for calling  Default value: 10

    #--panel-of-normals; VCF file of sites observed in normal.  Default value: null
    panelOfNormals: somatic-b37_Mutect2-exome-panel.vcf
    #--germline-resource; Population vcf of germline sequencing containing allele fractions.  Default value: null
    germlineResource: somatic-b37_af-only-gnomad.raw.sites.vcf

  filterMutectCalls:
    #--contamination-estimate 0.5?; Estimate of contamination.  Default value: 0.0 (evtl. tumor purity)
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-allele-fraction 0.05; Minimum allele fraction required  Default value: 0.0 (VAF?)
    #--min-median-base-quality 28; Minimum median base quality of alt reads  Default value: 20
  
  ControlFREEC:
    # desired behavior in the ambiguous regions (poly-N or low mappability regions between two different copy number values)
    # 0: the "unknown" region is attached to the "known" region on the right
    # 1: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one
    # 2: make a separate fragment of this unknown region and then attaches it to the left or to the right region but the ploidy copy number has a priority
    # 3: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one but this known region should make at least half-size of the unknown region
    # 4: make a separate fragment of this unknown region and do not assign any copy number to this region at all
    breakPointType: 4
    # positive value of threshold for segmentation of normalized profiles
    breakPointThreshold: 1.2
    # set to 1 or 2 to correct the Read Count (RC) for GC-content bias and low mappability even when you have a control sample
    # 0: simply model "sample RC ~ Control RC"
    # 1: normalize the sample and the control RC using GC-content and then calculate the ratio "Sample RC/contol RC"
    # 2: model "sample RC ~ Control RC" bias, and then normalize for GC-content
    forceGCcontentNormalization: 1
    # intercept of polynomial
    # 1 - with GC-content,
    # 0 - with a control dataset
    intercept: 1
    # minimal number of consecutive windows to call a CNA
    # 3 for WES and 1 for WGS
    minCNAlength: 3
    # maxThreads: 12 -> cpucores
    # set TRUE for target resequencing data (e.g., exome-seq) to avoid false positive predictions due to non-uniform capture
    noisyData: TRUE
    # genome ploidy; In case of doubt, you can set different values and Control-FREEC will select the one that explains most observed CNAs
    ploidy: 2
    # set FALSE to avoid printing "-1" to the _ratio.txt files. Useful for exome-seq or targeted sequencing data
    printNA: FALSE
    # threshold on the minimal number of reads per window in the control sample
    # Useful for exome-seq or targeted sequencing data
    # recommended value >=50 for for exome data
    readCountThreshold: 50
    # step (used only when "window" is specified); do not use for exome sequencing (instead set "window=0")
    step: 0
    # explicit window size (higher priority than coefficientOfVariation);
    # for whole genome sequencing: "window=50000"
    # for whole exome sequencing: "window=0"
    window: 0
    # Use a mappability profile to correct read counts (in this case a mappability file must be provided with "gemMappabilityFile" )
    uniqueMatch: TRUE
    # set TRUE to correct for contamination by normal cells.
    # If "contamination" is not provided, it will automatically evaluate the level of contamination
    contaminationAdjustment: TRUE
  
  fusions:
    fusionGenes: fusion_genes.txt
  amplification:
    amplificationGenes: TSO500_amplifications.txt

## tumorOnly Parameters
tumorOnly:
  mutect:
    #--base-quality-score-threshold 28; Base qualities below this threshold will be reduced to the minimum (6)  Default value: 18
    #--callable-depth 8; Minimum depth to be considered callable for Mutect stats.  Does not affect genotyping. Default value: 10
    callableDepth: 8
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-base-quality-score 28; Minimum base quality required to consider a base for calling  Default value: 10

    #--panel-of-normals; VCF file of sites observed in normal.  Default value: null
    panelOfNormals: somatic-b37_Mutect2-exome-panel.vcf
    #--germline-resource; Population vcf of germline sequencing containing allele fractions.  Default value: null
    germlineResource: somatic-b37_af-only-gnomad.raw.sites.vcf

  filterMutectCalls:
    #--contamination-estimate 0.5?; Estimate of contamination.  Default value: 0.0 (evtl. tumor purity)
    #--intervals V6UTR.bed; One or more genomic intervals over which to operate  This argument may be specified 0 or more times. Default value: null
    #--min-allele-fraction 0.05; Minimum allele fraction required  Default value: 0.0 (VAF?)
    #--min-median-base-quality 28; Minimum median base quality of alt reads  Default value: 20
  
  ControlFREEC:
    # desired behavior in the ambiguous regions (poly-N or low mappability regions between two different copy number values)
    # 0: the "unknown" region is attached to the "known" region on the right
    # 1: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one
    # 2: make a separate fragment of this unknown region and then attaches it to the left or to the right region but the ploidy copy number has a priority
    # 3: make a separate fragment of this unknown region and then attaches it to the left or to the right region choosing the longer one but this known region should make at least half-size of the unknown region
    # 4: make a separate fragment of this unknown region and do not assign any copy number to this region at all
    breakPointType: 4
    # positive value of threshold for segmentation of normalized profiles
    breakPointThreshold: 1.2
    # set to 1 or 2 to correct the Read Count (RC) for GC-content bias and low mappability even when you have a control sample
    # 0: simply model "sample RC ~ Control RC"
    # 1: normalize the sample and the control RC using GC-content and then calculate the ratio "Sample RC/contol RC"
    # 2: model "sample RC ~ Control RC" bias, and then normalize for GC-content
    forceGCcontentNormalization: 1
    # intercept of polynomial
    # 1 - with GC-content,
    # 0 - with a control dataset
    intercept: 1
    # minimal number of consecutive windows to call a CNA
    # 3 for WES and 1 for WGS
    minCNAlength: 3
    # maxThreads: 12 -> cpucores
    # set TRUE for target resequencing data (e.g., exome-seq) to avoid false positive predictions due to non-uniform capture
    noisyData: TRUE
    # genome ploidy; In case of doubt, you can set different values and Control-FREEC will select the one that explains most observed CNAs
    ploidy: 2
    # set FALSE to avoid printing "-1" to the _ratio.txt files. Useful for exome-seq or targeted sequencing data
    printNA: FALSE
    # threshold on the minimal number of reads per window in the control sample
    # Useful for exome-seq or targeted sequencing data
    # recommended value >=50 for for exome data
    readCountThreshold: 50
    # step (used only when "window" is specified); do not use for exome sequencing (instead set "window=0")
    step: 0
    # explicit window size (higher priority than coefficientOfVariation);
    # for whole genome sequencing: "window=50000"
    # for whole exome sequencing: "window=0"
    window: 0
    # Use a mappability profile to correct read counts (in this case a mappability file must be provided with "gemMappabilityFile" )
    uniqueMatch: TRUE
    # set TRUE to correct for contamination by normal cells.
    # If "contamination" is not provided, it will automatically evaluate the level of contamination
    contaminationAdjustment: TRUE
    
annovar:
  # define annotation databases, together with their type, used. The databases have to be installed with annovar
  protocol: 'refGene,gnomad211_genome,avsnp150,clinvar_20210501,intervar_20180118,dbnsfp42a,cosmic_coding,cosmic_noncoding'
  argop: 'g,f,f,f,f,f,f,f'

sequenza:
  # define sequenza-utils parameter
  # --window WINDOW; Window size used for binning the original seqz file. Default is 50.
  window: 50
  # if used for samples without mathcing normal as control a separate non-matching-normal file in bam format is needed
  # file should be stored in MIRACUM-Pipe-docker/assets/references/sequenza
  nonMatchingNormal: non_matching_normal.bam
  chromosomes: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX

reference:
  # define reference genome (located in references/Genome incl. indices)
  genome: genome.fa
  # file containing the length of the chromosomes (located in references/chromosomes)
  length: hg19_chr.len
  # reference wig file for HRD calculation; if not present its generated (to be put/created in databases)
  hrdRef: hg19all.wig.gz
  # microsatellite sites for msisnesor-pro; if not present its generated (to be put/created in databases)
  microsatelliteSites: microsatellite_sites_hg19
  # database of known SNPs (located in databses/dbSNP)
  dbSNP: snp150hg19.vcf.gz
  # Mappability file needed for calling CNVs with ControlFREEC (located in reference/mappability)
  mappability: out100m2_hg19.gem
  # file used for mane select database
  maneselect: MANE.GRCh38.v1.2.summary.txt
  sequencing: # all located in references/sequencing
    # target region covered by the sequencer in .bed format
    captureRegions: V5UTR.bed
    # file containing all the covered genes as HUGO Symbols
    captureGenes: V5UTR_Targets.txt
    # target region in Mega bases covered
    coveredRegion: 75
    # target / capture region kit name
    captureRegionName: V5UTR
    # target capture correlation factors for mutation signature analysis
    captureCorFactors : targetCapture_cor_factors.rda
    # covered exons by capture kit; basically intersection of exons with capture regions
    # e.g. bedtools intersect -u -a targets.bed -b bed_exons_hg19.bed > exons_Routine.bed
    coveredExons: exons_5UTR.bed
    # positive list for genes in germline to be reported (e.g. by ACMG)
    # actionableGenes: actionable_genes.txt
