name: Install Debian packages

on:
    push:
      paths:
        - debian/**  
        - docker/Dockerfile
        - docker/Dockerfile_base

jobs:

  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Debian packages in Docker container
      run: docker build . --file docker/Dockerfile_base